### ISSUE TITLE
Difference/overlap with css-vars-ponyfill

### ISSUE THREAD

**Issue by dogoku** [nuxodin/ie11CustomProperties#10]
Hi, I was wondering if you are aware of https://github.com/jhildenbiddle/css-vars-ponyfill and if yes, can you explain the difference between this polyfill and that one?

Thanks

**Comment by nuxodin** [comment]
Yes, I know the ponyfill, it allows CSS vars only on the :root element.
With my polyfill you have almost complete support for "CSS Custom Properties" including JS integration and not just :root variables.
Maybe the ponyfill is faster because it only accepts :root variables, but I didn't compare the performance,

**Comment by dogoku** [comment]
thanks for the clarification :)

**Comment by nuxodin** [comment]
be welcome :)

**Comment by nuxodin** [comment]
Just a friendly note: 
Please consider voting for this solution at Stackoverflow if you like my polyfill.
https://stackoverflow.com/a/57000437/4865307 and
https://stackoverflow.com/a/56830621/4865307 and
https://stackoverflow.com/a/57000620/4865307
